# Central DB Instance
database:
    driver: "ODBC Driver 17 for SQL Server"
    server: "COLO SQL Server"
    database: "<DB_Name>"
    username: "<db_username>"
    password: "<db_password>"

zabbix_instances:
    - url: "http://<zabbix_server_url>/zabbix"
      # We can use either token or username/password
      token: "<zabbix_api_token>"
      # OR
      # username: "<zabbix_username>"
      # password: "<zabbix_password>"
      plant_name: "<Plant_Name>"
      region: "Region"

    # Append more instances as needed
